// This file is from RainBOT.
// 
// Copyright(c) 2022 Bujju
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using DSharpPlus.SlashCommands;
using RainBOT.Core.Services;

namespace RainBOT.Modules
{
    [SlashCommandGroup("pronouns", "Try new pronouns to see if they fit.")]
    public class Pronouns : ApplicationCommandModule
    {
        public Data Data { private get; set; }

        [SlashCommand("try", "Try new pronouns.")]
        public async Task PronounsTryAsync(InteractionContext ctx,
            [Option("subjective", "He, she, and they are subjective pronouns.")] string subjective,
            [Option("objective", "Him, her, and them are objective pronouns.")] string objective,
            [Option("possessive-adjective", "His, her, and their are possessive adjectives.")] string possessiveAdjective,
            [Option("possessive-pronoun", "His, hers, and theirs are possessive pronouns.")] string possessivePronoun,
            [Option("reflexive", "Himself, herself, and themself are reflexive pronouns.")] string reflexive,
            [Option("plural", "Whether or not to use plural grammar rules for the pronouns.")] bool plural)
        {
            string[] prompts = new string[]
            {
                $"My friend {ctx.User.Username} and I went to the café the other day. Usually, " +
                $"I order for {objective}, but {subjective} ordered for {reflexive} today! I am " +
                $"really proud of {objective}.",

                $"Do you know where {ctx.User.Username} is? I think {subjective} lost " +
                $"{possessiveAdjective} phone. I found a phone, and it looks like " +
                $"{possessivePronoun}. The last time I saw {objective}, {subjective} " +
                $"{(plural ? "were" : "was")} over there. Oh, there {subjective} " +
                $"{(plural ? "are" : "is")}.",

                $"Did {ctx.User.Username} tell you that {subjective}'{(plural ? "re" : "s")} " +
                $"trying out {subjective}/{objective} pronouns. I think these pronouns fit " +
                $"{objective} really well. Do you think {subjective} made a good choice? I hope " +
                $"{subjective} can find pronouns that fit {objective}.",

                $"Have you met {ctx.User.Username}? You haven't? I think you'd like " +
                $"{objective}. {subjective}'{(plural ? "re" : "s")} really kind and funny. You " +
                $"should meet {objective} sometime."
            };

            await ctx.CreateResponseAsync(prompts[new Random().Next(prompts.Length)], true);
        }

        [SlashCommand("random", "Get a random set of pronouns to try.")]
        public async Task PronounsRandom(InteractionContext ctx)
        {
            // https://docs.google.com/spreadsheets/d/1_AHHBGKSzEKtKfZ9WqWAmUGuyfaIsrYmeoRkekC6VIA/edit?usp=sharing (Non-themed an non-exclusive only)
            string[] prompts = new string[]
            {
                "ae/aeir/aer/aers/aeirself",
                "ae/aem/aer/aers/aemself",
                "ae/aer/aer/aes/aeself",
                "ae/aer/aers/aers/aerself",
                "ae/aet/aet/aets/aetself",
                "aer/aer/aer/aers/aerself",
                "ala/alum/alis/alis/alumself",
                "ao/aos/aos/ao/aoself",
                "av/ave/avem/aveir/avemself",
                "ay/em/air/airs/emself",
                "be/ber/bers/berself",
                "be/berm/bers/bermself",
                "be/bim/bis/bimself",
                "bey (or be)/bem/beir/beirs/bemself",
                "bi/bir/bier/biers/bierself",
                "bleu/bleu/bleus/bleus/bleuself",
                "cae/caer/caers/caers/caerself",
                "ce/cem/cer/cers/cemself",
                "ce/cem/hir/hirs/hirself",
                "ce/cer/cers/cers/cerself",
                "ce/cer/ces/ces/ceself",
                "ce/cet/cets/cets/cetself",
                "ce/cim/cir/cirs/cirself",
                "ce/cir/cirs/cirs/cirself",
                "cer/cer/cers/cers/cerself",
                "che/chim/chis/chis/chimself",
                "che/hap/han/hans/hapself",
                "chi/chir/chirs/chirs/chirself",
                "ci/cim/cir/cirs/cimself",
                "cii/ciir/ciir/ciirs/ciirself",
                "co/cos/co's/co's/coself",
                "co/cos/cos/cos/coself",
                "cy/cyr/cyr/cyrs/cykeself",
                "dae/dae/daes/daes/daeself",
                "dae/daem/daer/daer/daemself",
                "dae/daer/daes/daes/daerself",
                "de/dem/deir/deir/demself",
                "de/dem/dems/dems/demself",
                "de/dim/dier/diers/dierself",
                "ðe/ðim/ðir/ðirs/ðimself",
                "dey/de/deir/deirs/deyself",
                "dhey/dhem/dher/dhers/dhemself",
                "di/div/divs/divs/divself",
                "di/div/divs/divs/divself (individual)",
                "dy/dym/dyr/dyrs/dymself",
                "e/'im/'er/'ers/'imself",
                "e/eir/eir/eirs/eirself",
                "e/em/e's/e's/emself",
                "e/em/eir/eirs/emself",
                "e/em/er/ers/emself",
                "e/em/es/ems/emself",
                "e/em/es/es/emself",
                "e/em/ir/irs/emself",
                "e/im/er/ers/imself",
                "e/rim/ris/ris/rimself",
                "ei/eim/eir/eirs/eimself",
                "em/em/ems/ems/emself",
                "en/en/ens/ens/enself",
                "er/ign/sein/sein/ihm",
                "et/em/eri/eris/etself",
                "et/ets/ets/ets/etself",
                "ex/ex/exs/exs/exself",
                "ey/em/eir/eirs/emself or eirself",
                "ey/em/eyr/eyrs/emself",
                "ey/eym/eyr/eyrs/eymself",
                "fa/fae/faes/faes/faeself",
                "fae/faem/faer/faers/faemself",
                "fae/faen/faer/faers/faenself",
                "fae/faen/faer/faers/faenself",
                "fae/faer/faers/faers/faerself",
                "fay/fayr/fays/fays/fayself",
                "fe/faer/faer/faers/faerself",
                "fe/fel/fiz/fizs/fizself",
                "fe/fyc/fycs/fycs/fycself",
                "fey/fem/feir/feirs/feyself",
                "fey/fer/fers/fers/ferself",
                "fey/feyr/feyrs/feyrs/feyrself",
                "fey/fir/fir/firs/firself",
                "fi/fer/fer/fers/ferself",
                "fie/fem/fir/firs/femself",
                "fie/fir/fir/firs/firself",
                "fir/fer/fer/fers/ferself",
                "fir/fir/fir/firs/firself",
                "ge/gem/gur/gurs/gemself",
                "ge/ger/ges/gers/gerself",
                "ge/ger/gis/gis/gerself",
                "ha/hem/hez/hez/hemself",
                "he or she/him or her/his or her/his or hers/himself or herself",
                "he'er/him'er/his'er/his'er's/his'er'self",
                "he/hem/hes/hes/hemself",
                "he/him/his/his/himself",
                "hes/hem/heir/heirs/hemself",
                "hey/hem/heir/heirs/hemself",
                "hi/hem/hes/hes/hemself",
                "hi/him/hir/hirs/himself",
                "hi/hir/hir/hirs/hirself",
                "hi/his/hive/hives/hiveself",
                "hie/hie/hiez/hiez/ov hie",
                "hie/hir/hirs/hirs/hemself",
                "hie/hym/hyr/hyrs/hymself",
                "hin/hin/hins/hins/hinself",
                "hir/hir/hir/hirs/hirself",
                "hizer/hizem/hizir/hizirs/hizemself",
                "ho/hom/hos/hos/homself",
                "hu/hum/hus/hus/huself",
                "hu/hume/humes/humes/humeself",
                "hu/hur/hurs/hurs/hurself",
                "hu/hus/hus/hus/huself",
                "hx/hxm/hxs/hxs/hxmself",
                "hy/hym/hys/hys/hymself",
                "hye/hyer/hyer/hyers/hyenself",
                "hyt/yim/yis/yis/yimself",
                "id/idre/ids/ids/idself",
                "ie/ier/ier/iers/ierself",
                "ip/im/ir/irs/imself",
                "ip/ip/ips/ips/ipsself",
                "ir/im/ir/irs/imself",
                "ir/im/iro/iros/iroself",
                "ir/ir/ir/irs/irself",
                "ir/ire/iro/iros/ireself",
                "it/it/its/its/itself",
                "ix/ix/ixs/ixs/ixself",
                "ix/ixen/ixens/ixens/ixenself",
                "ith/imth/irth/irths/imthself",
                "ja/jem/jems/jems/jemself",
                "jam/jam/jams/jams/jamself",
                "jay/jem/jaer/jaers/jemself",
                "je/jem/jer/jers/jhemself",
                "je/jer/jer/jers/jerself",
                "jee/jeir/jem/jems/jemself",
                "jhe/jem/jeir/jeirs/jemself",
                "jhe/jher/jher/jhers/jherself",
                "jhey/jheir/jheir/jheirs/jheirself",
                "jhey/jhem/jheir/jheirs/jhemself",
                "ji/jem/jir/jirs/jemself",
                "kai/kaim/kais/kais/kaiself",
                "kai/kair/kair/kairs/kairself",
                "kai/kais/kais/kais/kaiself",
                "ke/kem/keir/keirs/keirself",
                "ke/kem/keir/keirs/kemself",
                "ke/kem/kheir/kheirs/kemself",
                "ke/kem/kir/kirs/kemself",
                "kei/keir/keir/keirs/keirself",
                "kei/keir/keirs/keirs/keirself",
                "key/kyr/kyr/kyrs/kyrself",
                "ki/ker/ker/kers/kerself",
                "kie/kir/kir (or kirs)/kirs/kirself",
                "kir/kir/kirs/kirs/kirself",
                "kye/kyne/kyr/kyrs/kyrself or kyneself",
                "kye/kyr/kyr/kyrs/kyrself",
                "le/lem/les/les/lesself",
                "le/lim/lims/lims/limself",
                "le/lim/lir/lirs/lirself",
                "le/lim/lis/lis/limself",
                "lee/lim/lis/lis/limself",
                "li/lim/lims/lims/limself",
                "li/lir/lirs/lirs/lirself",
                "mae/mae/mair/maes/maeself",
                "mae/mer/mims/mims/merself",
                "mae/mim/mair/mairs/mairself",
                "mie/mem/mer/mers/memself",
                "mim/mim/myr/myrs/mimself",
                "mix/mex/mexs/mexs/mexself",
                "mo/mo/mo's/mo’s/moself",
                "mye/myr/myr/myrs/myrself",
                "mys/myr/myr/myrs/myrself",
                "na/nan/nan/nan's/naself",
                "nae/naem/naer/naers/naemself",
                "nae/nym/nyr/nyrs/nymself",
                "nai/nai/nai/nais/naiself",
                "ne/nem/neir/neirs/nemself",
                "ne/nem/nes/nes/nemself",
                "ne/nem/nes/nes/neself",
                "ne/nem/nir/nirs/nemself",
                "ne/nem/nir/nirs/nirself",
                "ne/neo/neos/neos/neoself",
                "ne/ner/neir/neirs/neirself",
                "ne/ner/ner/ners/nerself",
                "ne/ner/nerre/nerse/nerself",
                "ne/nim/nir/nirs/nimself",
                "ne/nim/nis/nis/nimself",
                "ne/nir/nir/nirs/nirself",
                "ne/nym/nir/nirs/nymself",
                "ne/nym/nis/nis/nymself",
                "ne/nym/nyr/nyrs/nymself",
                "ne/nym/nys/nys/nymself",
                "ney/nem/neir/neirs/nemself",
                "nin/nim/nims/nims/nimself",
                "nin/nim/nins/nins/ninself",
                "nis/nim/nir/nirs/nimself",
                "nix/nix/nix/nixs/nixself",
                "no", // To form "no pronouns"
                "no/non/nons/nons/nonself",
                "ny/nym/nys/nys/nymself",
                "o/oxy/oxys/oxys/oxyself",
                "one/one/one’s/one's/oneself",
                "one/one/ones/ones/oneself",
                "ons/oms/ors/ors/omself",
                "ot/ot/ots/ots/otself",
                "other/other/others/others/otherself",
                "ou/ou/ous/ous/ouself",
                "peh/pehm/peh's/peh's/pehmself",
                "per/per/per/pers/perself",
                "per/per/pers/pers/perself",
                "person/per/pers/pers/perself",
                "phe/per/pers/pers/perself",
                "phey/phem/pheir/pheirs/pheirself",
                "pic/pim/per/pers/pimself",
                "pur/pur/pur/purs/purself",
                "py/pyl/pyls/pyls/pylself",
                "py/pylx/pylx/pylx/pylxself",
                "qe/qer/qers/qem/qemself",
                "qu/qu/qus/qus/quself",
                "quoi/quim/quis/quis/quimself",
                "quoi/quoir/quoir/quoirs/quoirself",
                "re/erm/rees/rees/ermself",
                "re/rei/res/res/reiself",
                "re/rem/rheir/rheirs/remself",
                "re/ren/reis/reisi/reniself",
                "re/rhir/rhir/rhirs/rhirself",
                "rie/rhem/rer/rers/rerself",
                "s/he (or sHe with capital h)/ hir/hir/hirs/hirself",
                "s/he, h/er, h/er, h/ers, h/erself",
                "sae/saer/saer/saers/saerself",
                "saw/zaer/zaer/zaers/zaerself",
                "say/sair/sair/sairs/sairself",
                "se/hem/hes/hes/hemself",
                "se/hir/hir/hirs/hirself",
                "se/sem/ser/sers/serself or semself",
                "se/sem/ses/ses/semself",
                "se/sim/ser/sers/simself",
                "se/sim/ser/sers/simself",
                "se/sim/sis/sis/simself",
                "se/syr/sym/syrs/syrself or symself",
                "sei/sei/seir/seirs/seirself",
                "sei/seir/seir/seirs/seirself",
                "self/self/selfs/selfs/selfself",
                "she/her/her/hers/herself",
                "she/sheer/sheers/sheers/sheerself",
                "she/sher/shers/shers/sherself",
                "shi/zir/zir/zirs/zirself",
                "sho/sher/sher/shers/sherself",
                "sho/shom/shom’s/shom's/shomself",
                "shy/hyr/hyr/hyrs/hyrself",
                "sie/hir/hem/hems/hemself",
                "sie/hir/hen/hirs/henself",
                "sie/hir/hirs/hirs/hirself",
                "sie/mer/mer/mers/merself",
                "sie/sie/sier/siers/sierself",
                "sie/sier/sier/siers/sierself",
                "swe/swe/swes/swes/sweself",
                "te/ter/tem/ters/temself",
                "tey/tem/ter/ters/temself",
                "thae/thaer/thaer/thaers/thaerself",
                "the/thim/thir/thirs/thimself",
                "thee/har/har/hars/harself",
                "they/them/their/theirs/themself",
                "they/they's/they's/they's/theyself",
                "they/theys/theys/theys/theyself",
                "thi/thim/thits/thits/thimself",
                "this one/that one/that one’s/that one’s/that oneself",
                "thon/thom/thor/thors/thomself",
                "thon/thon/thons/thons/thonself",
                "thy/thym/thyr/thyr/thymself",
                "tre/trem/trer/trers/tremself",
                "ty/tyr/tym/tyms/tymself",
                "tyr/tyr/tyrs/tyrs/tyrself",
                "um/eh/er/ers/umself",
                "vae/vaem/vaer/vaers/vaerself",
                "vae/vaer/vaer/vaers/vaerself",
                "ve/vaer/vaers/vaers/vaerself",
                "ve/vair/vair/vairs/vairself",
                "ve/vem/ver/vers/vemself",
                "ve/vem/vir/virs/vemself",
                "ve/ven/veen/vens/venself",
                "ve/ven/ver/vers/verself or venself",
                "ve/ver/veir/veirs/verself",
                "ve/ver/ver/vers/verself",
                "ve/ver/vis/vis/verself",
                "ve/vim/vis/vis/vimself",
                "ve/vir/vir/virs/virself",
                "ve/vis/ver/vers/verself",
                "ve/vis/vir/virs/verself",
                "ver/ver/ver/vers/verself",
                "vey/vem/veir/veirs/vemself",
                "vey/vem/vyr/vyrs/vemself",
                "vi/vic/vic/vics/vicself",
                "vi/vim/vir/virs/virself",
                "vi/vir/vir/virs/virself",
                "vie/ver/vers/verselfver/",
                "vie/vir/vem/vems/verself",
                "vo/vos/vos/vos/vosself",
                "voh/vohs/vohs/vohs/vohself",
                "vy/vim/vir/virs/virself",
                "wy/wym/wyr/wyrs/wyrself",
                "xae/xaer/xaer/xaers/xaerself",
                "xe/hem/hir/hirs/hemself",
                "xe/hir/hir/hirs/hirself",
                "xe/xem/xer/xers/xemself",
                "xe/xem/xir/xirs/xemself",
                "xe/xem/xyr/xyrs/xemself",
                "xe/xem/xyr/xyrs/xemself (or xyrself)",
                "xe/xem/xyr/xyrs/xyemself",
                "xe/xim/xir/xirs/xirself",
                "xe/xim/xis/xis/ximself",
                "xe/xir/xir/xirs/xirself",
                "xer/xeir/xeir/xeirs/xeirself",
                "xet/xets/xet/xets/xetself",
                "xey/xem/xeir/xeirs/xemself",
                "xey/xem/xyr/xyrs/xemself",
                "xi/xem/xer/xers/xemself",
                "xie/hir/hir/hirs/hirself",
                "xie/xem/xyr/xyrs/xemself",
                "xie/xim/xis/xis/ximself",
                "xit/xits/xits/xits/xitself",
                "xt/xts/xts/xts/xtself",
                "xy/xym/xys/xyms/xymself",
                "xy/xyr/xyr/xyrs/xyrself",
                "xye/xyem/xyi/xyis/xyemself",
                "yey/yem/yeir/yeirs/yemself",
                "yo/yo/yos/yos/yoself",
                "yre/yre/yre/yres/yreself",
                "yt/yt/yts/yts/ytself",
                "ȝe/ȝim/ȝer/ȝers/ȝimself",
                "z/zuf/zufs/zufs/zufself",
                "za/zae/zas/zas/zaself",
                "zae/zaer/zaer/zaers/zaerself",
                "zae/zem/zaer/zaers/zemself",
                "zay/zir/zir/zirs/zirself",
                "ze/em/zeir/zeirs/zeirself",
                "ze/hir/hir/hirs/hirself",
                "ze/hir/hir/hirs/hirself (note)",
                "ze/mer/mzer/zers/zemself",
                "ze/mer/zer/zers/zemself",
                "ze/vaer/vaer/vaers/vaerself",
                "ze/zan/zans/zans/zanself",
                "ze/zem/zeir/zeirs/zemself or zeirself",
                "ze/zem/zes/zes/zirself",
                "ze/zer/zem/zers/zemself",
                "ze/zer/zer/zers/zerself",
                "ze/ziem/zier/ziers/ziemself",
                "ze/zim/zees/zees/zeeself",
                "ze/zim/zis/zis/zimself",
                "ze/zir/zir/zirs/zirself",
                "ze/zir/zir/zirs/zirself",
                "ze/zyr/zyr/zyrs/zyrself",
                "zed/zed/zeir/zeirs/zedself",
                "zee/zed/zeta/zetas/zedself",
                "zet/zets/zets/zets/zetself",
                "zey/zem/zeir/zeirs/zemself",
                "zhe/zer/zer/zers/zerself",
                "zhe/zher/zhem/zhems/zhemself",
                "zhe/zhim/zher/zhers/zherself",
                "zhe/zhim/zher/zhers/zhimself",
                "zhe/zhim/zhir/zhirs/zhirself",
                "zhe/zhir/zhir/zhirs/zhirself",
                "zhey/zhem/zheir/zheirs/zhemself",
                "zhi/hir/hir/hirs/hirself",
                "zhi/zhir/zhir/zhirs/zhirself",
                "zi/zis/zou/zei/zisself",
                "zie/hir/hir/hirs/hirself",
                "zie/sair/sair/sairs/sairself",
                "zie/vaer/vaer/vaers/vaerself",
                "zie/zem/zeir/zeirs/zemself",
                "zie/zim/zir/zirs/zimself",
                "zie/zir/zir/zirs/zirself",
                "zit/zit/zits/zits/zitself",
                "zme/zmyr/zmyrs/zmyrs/zmyrself",
                "zx/zxr/zxr/zxyz/zxyzself",
                "zy/zys/zys/zys/zyself",
                "zyd/zyd/zys/zys/zydself",
                "þe/þim/þir/þirs/þimself"
            };

            await ctx.CreateResponseAsync($"You should try **{prompts[new Random().Next(prompts.Length)]}** pronouns.", true);
        }
    }
}