name: "Bug"
description: "Report a bug or typo "
assignees: "BujjuIsDumb"
labels: "Bug"
body:
- type: markdown
  attributes:
    value: "### File a bug report"
- type: markdown
  attributes:
    value: "RainBOT's goal is to deliver the best possible experience, so we're sorry that you've encountered a bug! Depending on the severity of the bug, we will try to fix it as soon as possible."
- type: textarea
  attributes:
    label: "Describe the bug"
    description: "Give a summary of the bug."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Steps to reproduce"
    description: "Give instructions on how to recreate the bug."
    value: |
      1.
      2.
      3.
  validations:
    required: true
- type: textarea
  attributes:
    label: "Expected behavior"
    description: "What is supposed to happen?"
  validations:
    required: true
- type: textarea
  attributes:
    label: "Actual behavior"
    description: "What actually happens?"
  validations:
    required: true
